name: SonarQube scanner Python version

on: 
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      path_requirements:
        type: string
        required: true
      projectKey:
        type: string
        required: true
      projectBaseDir:
        type: string
        required: true
      bash_script: 
        type: string
        required: false
    secrets:
      SONAR_TOKEN:
          required: true
      SONAR_HOST_URL:
        required: true
      DISCORD_WEBHOOK:
        required: true


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run bash script if exists 
      if: ${{ inputs.bash_script != '' }}
      run: |
        echo "${{ inputs.bash_script }}" > script.sh
        chmod +x script.sh
        ./script.sh
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '${{ inputs.python_version}}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.path_requirements }}
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.projectKey }}
          -Dsonar.projectBaseDir=${{ inputs.projectBaseDir }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}