name: SonarQube scanner Node version
on: 
  workflow_call:
    inputs:
      node_version:
        required: true
        type: number
      branch: 
        required: true
        type: string
      projectKey:
        type: string
        required: true
      projectBaseDir:
        type: string
        required: true
      bash_script: 
        type: string
        required: false

    
    secrets:
      SONAR_TOKEN:
          required: true
      SONAR_HOST_URL:
        required: true


jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}
      - name: run bash script if exists 
        if: ${{ inputs.bash_script != '' }}
        run: |
          echo "${{ inputs.bash_script }}" > script.sh
          chmod +x script.sh
          ./script.sh
      - name: setup NodeJS
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install dependencies
        run: npm install 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.projectKey }}
            -Dsonar.projectBaseDir=${{ inputs.projectBaseDir }}
            -Dsonar.exclusions=**/*.java
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}